apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
  namespace: linlic-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        alibabacloud.com/eci: "true" 
      annotations:
        k8s.aliyun.com/eci-with-eip: "true"
        k8s.aliyun.com/eip-bandwidth: "1" 
    spec:
      containers:
        - env:
          - name: NACOS_URI
            value: https://nacos-test.ccmtv.cn/nacos
          - name: NACOS_PORT
            value: '443'
          - name: NACOS_USERNAME
            value: linlic_dev
          - name: NACOS_PASSWORD
            value: dS4$vNQeBRCS95GQ7hH3k
          - name: XXL_JOB_ADMIN_ADDRESS
            value: https://xxl-job-test.ccmtv.cn:443/xxl-job-admin
          name: ${APP_NAME}
          image: ${IMAGE}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      imagePullSecrets:
        - name: public-secret-acr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30